### GET All Books Happy Path
GET http://localhost:8080/api/v1/books
Authorization: Basic admin admin
Accept: application/json

###

### GET All Books Bad Credentials
GET http://localhost:8080/api/v1/books
Authorization: Basic admin1 admin
Accept: application/json

###

### GET without authorization (очікується 401)
GET http://localhost:8080/api/v1/books
Accept: application/json

###

### GET with wrong password
GET http://localhost:8080/api/v1/books
Authorization: Basic admin wrongpassword
Accept: application/json

###

### GET Book By Id
GET http://localhost:8080/api/v1/books/1
Authorization: Basic admin admin
Accept: application/json

###

### GET non-existent book
GET http://localhost:8080/api/v1/books/999
Authorization: Basic admin admin
Accept: application/json

###

### CREATE Book
POST http://localhost:8080/api/v1/books
Authorization: Basic admin admin
Content-Type: application/json

{
  "id": "4",
  "title": "name4",
  "author": "author4",
  "year": 2023
}

###

### 9. CREATE without authorization
POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "id": "5",
  "title": "hacker book",
  "author": "unknown",
  "year": 2026
}

###

### UPDATE Book
PUT http://localhost:8080/api/v1/books
Authorization: Basic admin admin
Content-Type: application/json

{
  "id": "1",
  "title": "updated name",
  "author": "updated author",
  "year": 2021
}

###

### DELETE Book
DELETE http://localhost:8080/api/v1/books/4
Authorization: Basic admin admin

###
